-- user-service schema: the legacy admin/customer/restaurant login tables unified into one table + role.
CREATE TABLE users (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,            -- BCrypt (legacy stored plaintext)
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('CUSTOMER','RESTAURANT','ADMIN')),
    phone         VARCHAR(20),
    gender        VARCHAR(10),
    address       VARCHAR(200),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP
);
CREATE INDEX idx_users_role ON users(role);