-- order-service schema: cart + orders + order lines, plus a local copy of menu items used for pricing.
CREATE TABLE menu_item_ref (
    menu_item_id  BIGINT PRIMARY KEY,            -- the menu item id
    name          VARCHAR(60)  NOT NULL,
    price         NUMERIC(9,2) NOT NULL,
    restaurant_id BIGINT       NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    quantity     INT    NOT NULL CHECK (quantity > 0),
    UNIQUE (user_id, menu_item_id)
);

CREATE TABLE orders (
    order_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    restaurant_id    BIGINT       NOT NULL,
    order_status     VARCHAR(20)  NOT NULL,
    total_amount     NUMERIC(9,2) NOT NULL,
    delivery_address VARCHAR(255) NOT NULL,
    payment_method   VARCHAR(20)  NOT NULL,
    created_at       TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at       TIMESTAMP
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT       NOT NULL REFERENCES orders(order_id),
    menu_item_id  BIGINT       NOT NULL,
    item_name     VARCHAR(60)  NOT NULL,
    unit_price    NUMERIC(9,2) NOT NULL,
    quantity      INT          NOT NULL,
    line_total    NUMERIC(9,2) NOT NULL
);
CREATE INDEX idx_cart_user ON cart_items(user_id);
CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_order_items_order ON order_items(order_id);

-- Seed the menu items used to price carts.
INSERT INTO menu_item_ref (menu_item_id, name, price, restaurant_id, active) VALUES
 (4,'Aloo Tiki',25.00,5,TRUE),(5,'Veg Burger',40.00,5,TRUE),(6,'Chicken Burger',60.00,5,TRUE),
 (7,'Onion Pizza',80.00,5,TRUE),(8,'Capsicum Pizza',80.00,5,TRUE),(9,'Samosa',10.00,5,TRUE),
 (10,'Manchurian',50.00,5,TRUE),(11,'White Sauce Pasta',110.00,5,TRUE),(12,'Red Sauce Pasta',90.00,5,TRUE),
 (13,'Onion & Capsicum Pizza',60.00,6,TRUE),(14,'Sweet Corn Pizza',70.00,6,TRUE),(15,'Extra Cheese Pizza',150.00,6,TRUE),
 (16,'Farm Pizza',200.00,6,TRUE),(17,'Simple Burger',30.00,7,TRUE),(18,'Veg Spicy Burger',40.00,7,TRUE),
 (19,'Simple Kulcha',20.00,7,TRUE),(20,'Aloo Patties',10.00,7,TRUE),(21,'Cream Sandwich',35.00,7,TRUE),
 (22,'Momos',20.00,7,TRUE),(23,'Coffee',30.00,7,TRUE),(24,'Cold Drink',20.00,7,TRUE),(25,'Mango Shake',40.00,7,TRUE);