-- restaurant-service schema (migrated from legacy MySQL `restaurant` + `menu`).
CREATE TABLE restaurants (
    restaurant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)  NOT NULL,
    email         VARCHAR(120) NOT NULL UNIQUE,
    phone         VARCHAR(20),
    address       VARCHAR(200),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP
);

CREATE TABLE menu_items (
    menu_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT       NOT NULL REFERENCES restaurants(restaurant_id),
    name          VARCHAR(60)  NOT NULL,
    type          VARCHAR(40)  NOT NULL,
    price         NUMERIC(9,2) NOT NULL,
    description   VARCHAR(500),
    active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP
);
CREATE INDEX idx_menu_items_restaurant ON menu_items(restaurant_id);

INSERT INTO restaurants (restaurant_id, name, email, phone, address, active) VALUES
 (5, 'Kohli Sweet',   'kohlisweet12@gmail.com', '9855344455', 'Main Road, Tripuri Town, Patiala', TRUE),
 (6, 'Dominik Pizza', 'dominikpizza@gmail.com', '9803080111', 'Old Janj Ghar, Tripuri Town, Patiala', TRUE),
 (7, 'Burger Point',  'burgerpoint@gmail.com',  '7888589924', 'Urban Estate Phase 2, Patiala', TRUE);

INSERT INTO menu_items (menu_item_id, restaurant_id, name, type, price, description, active) VALUES
 (4,5,'Aloo Tiki','Burger',25.00,'Aloo tikki with dahi and masala',TRUE),
 (5,5,'Veg Burger','Burger',40.00,'Burger with mayonnaise and salad',TRUE),
 (6,5,'Chicken Burger','Burger',60.00,'Crunchy chicken burger',TRUE),
 (7,5,'Onion Pizza','Pizza',80.00,NULL,TRUE),
 (8,5,'Capsicum Pizza','Pizza',80.00,NULL,TRUE),
 (9,5,'Samosa','Indian',10.00,NULL,TRUE),
 (10,5,'Manchurian','Chinese',50.00,NULL,TRUE),
 (11,5,'White Sauce Pasta','Italian',110.00,NULL,TRUE),
 (12,5,'Red Sauce Pasta','Italian',90.00,NULL,TRUE),
 (13,6,'Onion & Capsicum Pizza','Pizza',60.00,NULL,TRUE),
 (14,6,'Sweet Corn Pizza','Pizza',70.00,NULL,TRUE),
 (15,6,'Extra Cheese Pizza','Pizza',150.00,NULL,TRUE),
 (16,6,'Farm Pizza','Pizza',200.00,NULL,TRUE),
 (17,7,'Simple Burger','Burger',30.00,NULL,TRUE),
 (18,7,'Veg Spicy Burger','Burger',40.00,NULL,TRUE),
 (19,7,'Simple Kulcha','Kulcha',20.00,NULL,TRUE),
 (20,7,'Aloo Patties','Patties',10.00,NULL,TRUE),
 (21,7,'Cream Sandwich','Sandwich',35.00,NULL,TRUE),
 (22,7,'Momos','Chinese',20.00,NULL,TRUE),
 (23,7,'Coffee','Beverages',30.00,NULL,TRUE),
 (24,7,'Cold Drink','Beverages',20.00,NULL,TRUE),
 (25,7,'Mango Shake','Beverages',40.00,NULL,TRUE);